// <auto-generated />
namespace StudioManagement.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User));
        
        string IMigrationMetadata.Id
        {
            get { return "201510031418272_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
